org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.bundle.enableUncompressedNativeLibs=true

# Support for 16KB memory page sizes (Android 15+)
android.enableR8.fullMode=true
android.experimental.enableArtProfiles=true
