// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQ6bCl2ljwysVa2EZAMKlgSyvBpMsPTA',
    appId: '1:957851631152:web:8b9eb7658f9bda15ac77f5',
    messagingSenderId: '957851631152',
    projectId: 'xcode-fe06f',
    authDomain: 'xcode-fe06f.firebaseapp.com',
    storageBucket: 'xcode-fe06f.firebasestorage.app',
    measurementId: 'G-69TDRGR27M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIEZzg7EPVoQ494z_1deW455GKW4xUHLM',
    appId: '1:957851631152:android:017ca555e97c5e43ac77f5',
    messagingSenderId: '957851631152',
    projectId: 'xcode-fe06f',
    storageBucket: 'xcode-fe06f.firebasestorage.app',
    measurementId: 'G-69TDRGR27M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB0ALg1sDloMVx8-hW2yPI4mFCP6mbOgg',
    appId: '1:957851631152:ios:84d679f2d10ec83cac77f5',
    messagingSenderId: '957851631152',
    projectId: 'xcode-fe06f',
    storageBucket: 'xcode-fe06f.firebasestorage.app',
    iosBundleId: 'com.example.xcode360',
    measurementId: 'G-69TDRGR27M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB0ALg1sDloMVx8-hW2yPI4mFCP6mbOgg',
    appId: '1:957851631152:ios:84d679f2d10ec83cac77f5',
    messagingSenderId: '957851631152',
    projectId: 'xcode-fe06f',
    storageBucket: 'xcode-fe06f.firebasestorage.app',
    iosBundleId: 'com.example.xcode360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQ6bCl2ljwysVa2EZAMKlgSyvBpMsPTA',
    appId: '1:957851631152:web:092654e5a15b6115ac77f5',
    messagingSenderId: '957851631152',
    projectId: 'xcode-fe06f',
    authDomain: 'xcode-fe06f.firebaseapp.com',
    storageBucket: 'xcode-fe06f.firebasestorage.app',
    measurementId: 'G-2LDCN7SPE0',
  );

}